Add Chinese
ChiefArug/ThermalSysteams pull request #20
Opened 2024-07-21 05:06 UTC by krzj

2024-07-21 12:03 UTC, ChiefArug commented
Thanks for this! I'll have a proper look at it within the week, and hopefully get a release out with it by next week!

2024-08-12 16:38 UTC, cainiaojun requested changes
1. 很多锅炉的描述文本仅仅是把原版能源炉描述文本中的“RF”换成了“蒸汽”，从译名标准化的角度考虑，似乎应该和热力原版的翻译保持一致。
2. 文本中存在错别字（第8行“潜行队锅炉使用令其转变为发电机,返回锅炉蒸汽热管”中的“对”）
3. 没有全部使用全角标点.
因此我提议进行调整。

1. Many of the boilers' descriptions are simply replacing the word "RF" with "steam" in the original dynamos' descriptions. Therefore, from the point of view of translation standardization , those lines seems to be in line with the original translation in Thermal Series.
2. There are typos in the text (the word "对“ in line 8 "潜行队锅炉使用令其转变为发电机，返回锅炉蒸汽热管”)
3.  The full-width punctuation should be used in Chinese texts, which this translation failed to do.
So I propose that this translation be adjusted.

2024-08-17 02:53 UTC, krzj commented
> [zh_cn.json](https://github.com/user-attachments/files/16589640/zh_cn.json)
> 
> 1. 很多锅炉的描述文本仅仅是把原版能源炉描述文本中的“RF”换成了“蒸汽”，从译名标准化的角度考虑，似乎应该和热力原版的翻译保持一致。
> 2. 文本中存在错别字（第8行“潜行队锅炉使用令其转变为发电机,返回锅炉蒸汽热管”中的“队”应为“对”）
> 3. 没有全部使用全角标点. 因此，我提议进行调整。我把我调整后的翻译文本作为附件上传了。
> 4. 许多锅炉的描述只是简单地将原始发电机描述中的“RF”一词替换为“蒸汽”。因此，从翻译标准化的角度来看，那些台词似乎与热系列中的原始翻译是一致的。
> 5. 文中有错别字（第8行“潜行队锅炉使用令其转变为发电机，返回锅炉蒸汽热管”中的“队”一词，应为“对”）
> 6. 中文文本中应使用全角标点符号，而这次翻译没有做到。 所以我建议对这个翻译进行调整。附件是我调整的新翻译。
你要不再开个pr，我不太会操作

2024-08-17 02:56 UTC, cainiaojun commented
> > [zh_cn.json](https://github.com/user-attachments/files/16589640/zh_cn.json)
> > 
> > 1. 很多锅炉的描述文本仅仅是把原版能源炉描述文本中的“RF”换成了“蒸汽”，从译名标准化的角度考虑，似乎应该和热力原版的翻译保持一致。
> > 2. 文本中存在错别字（第8行“潜行队锅炉使用令其转变为发电机,返回锅炉蒸汽热管”中的“队”应为“对”）
> > 3. 没有全部使用全角标点. 因此，我提议进行调整。我把我调整后的翻译文本作为附件上传了。
> > 4. 许多锅炉的描述只是简单地将原始发电机描述中的“RF”一词替换为“蒸汽”。因此，从翻译标准化的角度来看，那些台词似乎与热系列中的原始翻译是一致的。
> > 5. 文中有错别字（第8行“潜行队锅炉使用令其转变为发电机，返回锅炉蒸汽热管”中的“队”一词，应为“对”）
> > 6. 中文文本中应使用全角标点符号，而这次翻译没有做到。 所以我建议对这个翻译进行调整。附件是我调整的新翻译。
> >    你要不再开个pr，我不太会操作

把我的附件下载下来。然后回到你自己的库，找到你的翻译文件，用我的替换掉（或者你自己改掉），保存，发commit，会自动同步到这的。
或者你就在这个页面按键盘上的句号键，可以打开一个在线VSCode，在里面做替换然后发commit就行

2024-08-17 08:58 UTC, cainiaojun approved these changes
No Problem Now.
现在应该没问题了。

2024-09-09 09:29 UTC, ChiefArug commented
Thank you both for this!

2024-09-09 09:30 UTC, merged